version: "3.7"
services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - 3000:3000
    command: npm run dev
    env_file:
      - .env
  
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brain_agriculture
    volumes:
      - brain_agriculture_pg_data:/postgres'

volumes:
  brain_agriculture_pg_data: